version: "3.9"
name: default
services:
  nginx:
    container_name: nginx_${PROJECT_NAME}
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www
      - ../logs/nginx:/var/log/nginx
    links:
      - php
      - db

  php:
    container_name: php_${PROJECT_NAME}
    build: ./php
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ../logs/php:/var/log
    links:
      - db

  db:
    container_name: postgres_${PROJECT_NAME}
    image: postgres:latest
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_default:/var/lib/mysql:rw
    ports:
      - "5432:5432"

volumes:
  db_default:

networks:
  default:
